package com.rus_cns_mon.pub_rus_cns_all_bre_data_rule_editing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class cns_combined_model implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public cns_combined_model() {
    }




}